export function getType(race: string | undefined) {
  switch (race) {
    case "Aqua":
      return "/img/tipos/Aqua.webp";
    case "Beast-Warrior":
      return "/img/tipos/Beast-Warrior.webp";
    case "Beast":
      return "/img/tipos/Beast.webp";
    case "Continuous":
      return "/img/tipos/Continuous.webp";
    case "Counter":
      return "/img/tipos/Counter.webp";
    case "Creator-God":
      return "/img/tipos/Creator-God.webp";
    case "Cyberse":
      return "/img/tipos/Cyberse.webp";
    case "Dinosaur":
      return "/img/tipos/Dinosaur.webp";
    case "Divine-Beast":
      return "/img/tipos/Divine-Beast.webp";
    case "Dragon":
      return "/img/tipos/Dragon.webp";
    case "Equip":
      return "/img/tipos/Equip.webp";
    case "Fairy":
      return "/img/tipos/Fairy.webp";
    case "Field":
      return "/img/tipos/Field.webp";
    case "Fish":
      return "/img/tipos/Fish.webp";
    case "Insect":
      return "/img/tipos/Insect.webp";
    case "Machine":
      return "/img/tipos/Machine.webp";
    case "Plant":
      return "/img/tipos/Plant.webp";
    case "Pyro":
      return "/img/tipos/Pyro.webp";
    case "Quick-Play":
      return "/img/tipos/Quick-Play.webp";
    case "Reptile":
      return "/img/tipos/Reptile.webp";
    case "Ritual":
      return "/img/tipos/Ritual.webp";
    case "Rock":
      return "/img/tipos/Rock.webp";
    case "Sea-Serpent":
      return "/img/tipos/Sea-Serpent.webp";
    case "Spellcaster":
      return "/img/tipos/Spellcaster.webp";
    case "Thunder":
      return "/img/tipos/Thunder.webp";
    case "Warrior":
      return "/img/tipos/Warrior.webp";
    case "Winged-Beast":
      return "/img/tipos/Winged-Beast.webp";
    case "Wyrm":
      return "/img/tipos/Wyrm.webp";
    case "Zombie":
      return "/img/tipos/Zombie.webp";
    case "Psychic":
      return "/img/tipos/Psychic.webp";
    case "Normal":
      return "/img/tipos/Normal.svg";
  }
}
